# Taken from the Rust Book
name: Cargo Build

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup update stable && rustup default stable
      - run: cargo build --verbose
#      - run: cargo test --verbose # We don't have proper test cases in the repo right now, so skip for now
